#!/bin/bash

source ./account.bash
source ./utility.bash
source ./simulations.bash

# CONSTANTS

UPDATE_TIME=60 # seconds	
BIN="./lazy_files/"
ACCOUNT=""


determine_action(){
	if [ $# -lt 1 ] || [ "$1" == "help" ]; then
		cat "${BIN}help.txt"
		return
	fi
	
	load_account
	
	# load make accounts
	if [ "$1" == "account" ]; then

		manage_account "${@}"
		return
	fi
	if [ -z "$ACCOUNT" ]; then
		echo "Make or select an account before other actions using account new or account switch"
		return
	fi
	
	# actions 
	if [ "$1" == "fish" ] || [ "$1" == "woodcut" ] || [ "$1" == "mine" ]; then
		if [ "$2" == "help" ] || [ -z "$2" ]; then
			$1 "help"
		elif [ -n "$3" ] && [ "$3" == "help" ]; then
			$1 $2 $3
		else
			set_task "$1" "$2"
		fi
	elif [ "$1" == "check" ]; then
		check_task
	elif [ "$1" == "inventory" ]; then
		show_inventory "${@}"
	elif [ "$1" == "stats" ]; then
		show_stats "${@}"
	else
		echo "No task/action called $1 see help if you are uncertain. Sorry"
	fi
}

# STAT SHOW FUNCTIONS

# show the levels of the player
#	optional stats to print otherwise all of them are printed
show_stats(){
	local all_stats=("fishing" "woodcuting", "mineing")
	if [ $# -gt 1 ]; then
		echo "FILTERED LEVELS (${ACCOUNT}):"
		for stat in "${@:2}"; do
			show_level "$stat"
		done
	else
		echo "LEVELS (${ACCOUNT}):"
		for stat in "${all_stats[@]}"; do
			show_level "$stat"
		done
	fi
}

# print the level 
# 	1. The stat to print
show_level(){
	local exp="$(get_value_from_file "${1}" "${ACCOUNT}/levels.txt")"
	local level="$(exp_to_lvl "$exp")"
	local next_level_xp
	if [ "$level" -eq 100 ]; then
		next_level_xp="MAX!!"
		echo "  $stat lvl: $level (${next_level_xp})"
	else
		next_level_xp="$(echo "${xp_values[$level]}" - "${exp}" | bc)"
		echo "  $stat lvl: $level (${next_level_xp}xp until next lvl)"
	fi
}


#get the level for a certain skill by the name of the stat e.g fishing
#	1. name of the stat
get_lvl(){
	local exp="$(get_value_from_file "${1}" "${ACCOUNT}/levels.txt")"
	local lvl=""
	if [ -n "$exp" ]; then
		lvl="$(exp_to_lvl "$exp")"
	fi
	echo "$lvl"
}

# pre calculated values for formula 25 * log10(xp + 100) - 50
xp_values=(10 21 32 45 59 74 91 109 130 152 176 202 232 264 299 337 379 425 476 531 592 659 732 813 901 997 1103 1219 1346 1485 1638 1806 1990 2191 2412 2655 2920 3212 3531 3882 4266 4687 5149 5655 6210 6819 7486 8218 9021 9900 10865 11923 13083 14355 15749 17279 18955 20793 22809 25019 27443 30100 33014 36208 39711 43552 47764 52381 57444 62996 69084 75758 83077 91102 99900 109548 120127 131726 144444 158390 173681 190447 208830 228987 251089 275323 301896 331032 362979 398008 436416 478531 524708 575340 630858 691731 758478 831664 911911 999901)
exp_to_lvl(){
	local lvl=0
	for val in "${xp_values[@]}"; do
		if [ $((val+0)) -gt $(($1+0)) ]; then
			echo $lvl
			return
		fi
		((lvl++))
	done
	echo 100
}

# TASK MANAGEMENT FUNCTIONS

# Set a task to perform with a location
#	1. the name of the task
#	2. the task location
set_task(){
	
	local min_name="${1}_${2}_min_lvl"
	local min_lvl="${!min_name}"
	local level="$(get_lvl "${1}ing")"
	
	local array_name="$1_locations"
	local location_array="$array_name[@]"
	local location_array=("${!location_array}")

	if [[ ! "${location_array[@]}" =~ "${2}" ]]; then
		echo "No location $2 for task $1"
		return
	elif [ $(($min_lvl+0)) -gt $(($level+0)) ]; then
		echo "Minum required ${1}ing level for ${1}ing at the ${2} is $min_lvl you are $level. Keep training..."
		return
	fi
	
	echo "Stopping current action..."
	check_task
	echo ""
	
	local task_name="$(get_value_from_file "last task" "${ACCOUNT}/general.txt")"
	set_value_in_file "last task" "${task_name}" "$1" "${ACCOUNT}/general.txt"
	
	local task_location="$(get_value_from_file "location task" "${ACCOUNT}/general.txt")"
	set_value_in_file "location task" "${task_location}" "$2" "${ACCOUNT}/general.txt"
	
	echo "Started ${1}ing at the $2"
}

# Run the simulate task function with the safety of checking if a task is currently running or not
# this function is for notifying the user what happened
check_task(){
	local task_name="$(get_value_from_file "last task" "${ACCOUNT}/general.txt")"
	if [ -z "$task_name" ]; then
		return
	fi

	local task_location="$(get_value_from_file "location task" "${ACCOUNT}/general.txt")"
	if [ -z "$task_location" ]; then
		return
	fi
	
	local current_lvl="$(get_lvl "${task_name}ing")"
	simulate_action $task_name $task_location
	local level="$(get_lvl "${task_name}ing")"

	if [ ! $(($current_lvl+0)) -eq $(($level+0)) ]; then
		echo "${ACCOUNT} ${task_name}ing level went from $current_lvl to $level."
	fi
}

# simulate an action for the time that the player has performed the action
#	1. name of task
#	2. location of task
simulate_action(){
	local task_name="$1"
	local task_location="$2"
	
	local last_time_stamp="$(get_value_from_file "last time stamp" "${ACCOUNT}/general.txt")"
	local current_time
	current_time="$(date +%s)"
	set_value_in_file "last time stamp" "$last_time_stamp" "$current_time" "${ACCOUNT}/general.txt"
	local elapsed_seconds=$(($((current_time+0))-$((last_time_stamp+0))))
	elapsed_seconds=$((elapsed_seconds+5000))
	local elapsed_time="$(get_elapsed_time "${elapsed_seconds}")"
	echo "${ACCOUNT} has ${task_name}ed for $elapsed_time. Now for the spoils:"
	
	$task_name $task_location $elapsed_seconds
	
	local index=0
	local array_name="${task_name}_${task_location}_array"
	local array="$array_name[@]"
	local array=("${!array}")
	local got_item=false
	
	# put all collected items in inventory
	for element in "${simulation_result[@]}"; do
		if [ $((element)) -gt 0 ]; then
			add_item_in_inventory "${array[index]}" "${element}"
			echo "  ${ACCOUNT} collected ${element} ${array[index]}!"
			got_item=true
		fi
		((index++))
	done
	if [ "$got_item" == false ]; then
		echo "  ${ACCOUNT} collected nothing lol"
		return
	fi
	#save the xp
	local orig_exp="$(get_value_from_file "${task_name}ing" "${ACCOUNT}/levels.txt")"
	local new_total=$(($((orig_exp+0))+$((exp_gained))))
	set_value_in_file "${task_name}ing" "$orig_exp" "$new_total" "${ACCOUNT}/levels.txt"
	echo "${ACCOUNT} gained $exp_gained ${task_name}ing XP."
}

# Show the inventory 
show_inventory(){
	if [ $# -gt 1 ]; then
		echo "FILTERED INVENTORY (${ACCOUNT}):"
		for item in "${@:2}"; do
			local item_quantity="$(get_value_from_file "$item" "${ACCOUNT}/inventory.txt")"
			if [ -n "$item_quantity" ]; then
				echo "  $item: $item_quantity"
			fi
		done
	else
		echo "INVENTORY (${ACCOUNT}):"
		local index=1
		while IFS= read -r line; do
			echo "  $index. $line"
			((index++))
		done < "${BIN}${ACCOUNT}/inventory.txt"
	fi
}

# Get the index in a lvl array that contains all levels below the given level 
# 	NOTE: the provided level should never be below the minimum required level
#	1. level
#	2. level array
get_max_arry_index(){
	local array=("${@:2}")
	local i=0
	local prev_value=0
	for i in "${!array[@]}"; do
		if (($1 >= $prev_value && "${array[$i]}" > $1)); then
			((i--))
			echo "$i"
			return
		fi
		prev_value="${array[$i]}"
	done
	echo "$i"
}

# return an index based on a wheighted input array
#	1. total wheight
#	2. wheight array
wheighted_roll(){
	local array=("${@:2}")
	local random_number=$((1 + RANDOM % $(($1))))
	local i=0
	local prev_value=0
	for i in "${!array[@]}"; do
		if (($random_number >= $prev_value && "${array[$i]}" >= $random_number)); then
			echo "$i"
			return
		fi
		prev_value="${array[$i]}"

	done
	echo "$i"
}

determine_action "${@}"